main: me.ender.core.Core
name: EnderCore
description: Test
version: 0.1.0
author: EnderGS
api-version: 1.17
#softdepend: [ProtocolLib]
commands:
  ecore:
    description: A great command
    permission: ender.core.ecore
  ecustom:
    description: Custom object
    permission: ender.core.ecustom
  eenchant:
    description: Custom enchants
    permission: ender.core.eenchant
  egui:
    description: Custom item interface
    permission: ender.core.egui
permissions:
  ender.core.*:
    description: All
    children:
      ender.core.ecore: true
      ender.core.enchant: true
      ender.core.ecustom: true
  ender.core.ecore:
    description: IDK
  ender.core.enchant:
    description: Hello
  ender.core.ecusom:
    description: The goto for custom items
  ender.core.egui:
    description: An awesome interface for custom items
    default: true
    children:
      ender.core.egui.admin: false
  ender.core.egui.admin:
    description: The ability to access the admin panel
  ender.core.nocooldown:
    description: Avoids cooldown for abilities;