main: me.ender.core.Core
name: EnderCore
description: Test
version: 0.1.0
author: EnderGS
api-version: 1.17
#softdepend: [ProtocolLib]
commands:
  ecore:
    description: A great command
    permission: ender.core.ecore
  ecustom:
    description: Custom object
  eenchant:
    description: Custom enchants
permissions:
  ender.core.*:
    description: All
  ender.core.ecore:
    description: IDK
  ender.core.enchant:
    description: Hello
    children:
      ender.core.enchant.unsafe: false
